version: '3.6'
services:

  postgres:
    container_name: jpa-shop_postgres
    image: postgres:13.1
    ports:
      - 6666:5432
    environment:
      - POSTGRES_PASSWORD=1111
      - POSTGRES_DB=jpashop
      - TZ=Asia/Seoul
      - LC_ALL=C.UTF-8
      - LC_COLLATE=C