version: '3.6'
services:

  postgres:
    container_name: jpa-shop_postgres
    image: postgres:13.1
    ports:
      - 6666:6543
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: postgres -c 'max_connections=1000'
    environment:
      - TZ=Asia/Seoul
      - LC_ALL=C.UTF-8
      - LC_COLLATE=C