server.port: 8081

spring:
  application.name: jpa-shop
  profiles:
    active: local

  datasource:
    driver-class-name: ${DB_DRIVER_CLASS_NAME:org.postgresql.Driver}
    url: ${DB_URL:jdbc:postgresql://127.0.0.1:6666/jpashop}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    open-in-view: false
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    database-platform: ${DB_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQL82Dialect}

logging:
  level:
    org.hibernate.SQL: debug
